### ISSUE TITLE
Bug: running BASQ sometimes fails if SOBER got too much training data

### ISSUE THREAD

**Issue by YannickNoelStephanKuhn** [ma921/SOBER#7]
When running BASQ on a SOBER-optimized model for further calculations, sometimes a cryptic error shows up:

```
Traceback (most recent call last):
    MAP = basq.MAP(map_samples)
  File "sober/BASQ/_basq.py", line 135, in MAP
    samples = self.sampler.sample(n_samples)
  File "sober/_sampler.py", line 427, in sample
    samples = torch.vstack([samples_wkde, samples_prior])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 0 but got size 5 for tensor number 1 in the list.
```

I printed the shapes of `samples_wkde` and `samples_prior` (in that order) to look at what happens here. When everything runs well, the output looks like this:
```
Expected log marginal likelihood: 8.68782e+00
Variance log marginal likelihood: -1.30538e+01
torch.Size([995, 5]) torch.Size([0, 5])
torch.Size([39, 5]) torch.Size([0, 5])
```
This is when I only run one SOBER iteration. But when I run 10 iterations, afterwards the output is:
```
Expected log marginal likelihood: 7.21550e+00
Variance log marginal likelihood: -1.73687e+01
torch.Size([618, 5]) torch.Size([0, 5])
torch.Size([0]) torch.Size([0, 5])
```
Which obviously can't be stacked.

I have two questions. Why is `samples_prior` always empty? And why is `samples_wkde` sometimes shaped wrongly?

Settings to reproduce: run SOBER with the following sample sizes for 1 or 10 iterations:
- 100 samples from the prior
- sober.next_batch(10000, 100, 100)
Then, run BASQ with the following sample sizes:
- basq.quadrature(200, 5, 5)
- basq.sampling_posterior(10)
- basq.MAP(100)

**Comment by YannickNoelStephanKuhn** [comment]
Note: it can also happen for small sample sizes, just had it happen for 26 samples in total. Seems to be a random issue with low probability.

**Comment by YannickNoelStephanKuhn** [comment]
It would seem that this "bug" is the result of an unsampleable posterior. So I just made the code correct the shape:
In https://github.com/ma921/SOBER/pull/8/commits/fc1cb99121fc918ce097b0620c376f01335990b1
In case this happens, ratio_wkde (in the instantiation of BASQ) should be set to something lower than 1, so at least some prior samples remain.
